node makeDrillFiles.js drill_input/chain1_stairs.json "Histy Pack Nov 2 '18 - Chain 1 Stairs" playermade/histy_nov2 chain1_stairs auto "false"
node makeDrillFiles.js drill_input/chain2_sandwich.json "Histy Pack Nov 2 '18 - Chain 2 Sandwich" playermade/histy_nov2 chain2_sandwich auto "false"
node makeDrillFiles.js drill_input/chain3_gtr.json "Histy Pack Nov 2 '18 - Chain 3 GTR" playermade/histy_nov2 chain3_gtr auto "false"
node makeDrillFiles.js drill_input/chain4_flat.json "Histy Pack Nov 2 '18 - Chain 4 Flat Stacking" playermade/histy_nov2 chain4_flat auto "false"
node makeDrillFiles.js drill_input/chain5_gtr.json "Histy Pack Nov 2 '18 - Chain 5 GTR" playermade/histy_nov2 chain5_gtr auto "false"
node makeDrillFiles.js drill_input/chain6_sandwich.json "Histy Pack Nov 2 '18 - Chain 6 Sandwich" playermade/histy_nov2 chain6_sandwich auto "false"
node makeDrillFiles.js drill_input/chain7_gtrlong.json "Histy Pack Nov 2 '18 - Chain 7 New GTR" playermade/histy_nov2 chain7_gtrlong auto "false"
node makeDrillFiles.js drill_input/chain8_gtr.json "Histy Pack Nov 2 '18 - Chain 8 GTR" playermade/histy_nov2 chain8_gtr auto "false"
node makeDrillFiles.js drill_input/chain9_lshape.json "Histy Pack Nov 2 '18 - Chain 9 L-Shape" playermade/histy_nov2 chain9_lshape auto "false"
node makeDrillFiles.js drill_input/chain10_sandwich.json "Histy Pack Nov 2 '18 - Chain 10 Sandwich" playermade/histy_nov2 chain10_sandwich auto "false"
node makeDrillFiles.js drill_input/chain11_sandwich.json "Histy Pack Nov 2 '18 - Chain 11 Sandwich" playermade/histy_nov2 chain11_sandwich auto "false"
node makeDrillFiles.js drill_input/chain12_avalanche.json "Histy Pack Nov 2 '18 - Chain 12 Avalanche" playermade/histy_nov2 chain12_avalanche auto "false"
node makeDrillFiles.js drill_input/chain13_flat.json "Histy Pack Nov 2 '18 - Chain 13 Flat Stacking" playermade/histy_nov2 chain13_flat auto "false"
node makeDrillFiles.js drill_input/chain14_lshape.json "Histy Pack Nov 2 '18 - Chain 14 L-Shape" playermade/histy_nov2 chain14_lshape auto "false"
node makeDrillFiles.js drill_input/chain15_sandwich.json "Histy Pack Nov 2 '18 - Chain 15 Sandwich" playermade/histy_nov2 chain15_sandwich auto "false"
node makeDrillFiles.js drill_input/chain16_sullengtr.json "Histy Pack Nov 2 '18 - Chain 16 Fukigen GTR" playermade/histy_nov2 chain16_ auto "false"
node makeDrillFiles.js drill_input/chain17_kumastacking.json "Histy Pack Nov 2 '18 - Chain 17 Kuma Stacking" playermade/histy_nov2 chain17_kumastacking auto "false"
node makeDrillFiles.js drill_input/chain18_flat.json "Histy Pack Nov 2 '18 - Chain 18 Flat Stacking" playermade/histy_nov2 chain18_flat auto "false"
node makeDrillFiles.js drill_input/chain19_sandwich.json "Histy Pack Nov 2 '18 - Chain 19 Sandwich" playermade/histy_nov2 chain19_sandwich auto "false"
node makeDrillFiles.js drill_input/chain20_kumastacking.json "Histy Pack Nov 2 '18 - Chain 20 Kuma Stacking" playermade/histy_nov2 chain20_kumastacking auto "false"
