node makeDrillFiles.js drill_input/4chain_tanakaspecial.json "4 Chain - Tanaka Special" tailing 4chain_tanakaspecial_nov2 manual "true" "Target: 4 Chain"
node makeDrillFiles.js drill_input/5chain_stairs.json "5 Chain - Stairs" stairs 5chain_stairs_nov2 manual "true" "Target: 5 Chain"
node makeDrillFiles.js drill_input/6chain_3columntail.json "6 Chain - 3 Column Avalanche" tailing 6chain_3columnavalanche_nov2 manual "true" "Target: 6 Chain"
node makeDrillFiles.js drill_input/7chain_gtr_a.json "7 Chain - GTR" gtr 7chain_GTR_nov2 manual "true" "Target: 7 Chain"
node makeDrillFiles.js drill_input/8chain_3columntail.json "8 Chain - Avalanche" tailing 8chain_avalanche_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_3columntail_b.json "8 Chain - Avalanche" tailing 8chain_avalanche_b_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_sandwich.json "8 Chain - Sandwich" sandwich 8chain_sandwich_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_sandwich_b.json "8 Chain - Sandwich" sandwich 8chain_sandwich_b_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_sandwich_lshape.json "8 Chain - Sandwich & L-Shape" sandwich 8chain_sandwich_lshape_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_yayoi.json "8 Chain - Yayoi" yayoi 8chain_yayoi_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/9chain_fukigen_GTR.json "9 Chain - Fukigen GTR" fukigen 9chain_fukigen_GTR_nov2 manual "true" "Target: 9 Chain"