node makeDrillFiles.js drill_input/4chain_tanakaspecial.json "4 Chain - Tanaka Special" tailing 4chain_tanakaspecial_nov2 manual "true" "Target: 4 Chain"
node makeDrillFiles.js drill_input/5chain_stairs.json "5 Chain - Stairs" stairs 5chain_stairs_nov2 manual "true" "Target: 5 Chain"
node makeDrillFiles.js drill_input/6chain_3columntail.json "6 Chain - 3 Column Avalanche" tailing 6chain_3columnavalanche_nov2 manual "true" "Target: 6 Chain"
node makeDrillFiles.js drill_input/7chain_gtr_a.json "7 Chain - GTR" gtr 7chain_GTR_nov2 manual "true" "Target: 7 Chain"
node makeDrillFiles.js drill_input/8chain_3columntail.json "8 Chain - Avalanche" tailing 8chain_avalanche_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_3columntail_b.json "8 Chain - Avalanche" tailing 8chain_avalanche_b_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_sandwich.json "8 Chain - Sandwich" sandwich 8chain_sandwich_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_sandwich_b.json "8 Chain - Sandwich" sandwich 8chain_sandwich_b_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_sandwich_lshape.json "8 Chain - Sandwich & L-Shape" sandwich 8chain_sandwich_lshape_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/8chain_yayoi.json "8 Chain - Yayoi" yayoi 8chain_yayoi_nov2 manual "true" "Target: 8 Chain"
node makeDrillFiles.js drill_input/9chain_fukigen_GTR.json "9 Chain - Fukigen GTR" fukigen 9chain_fukigen_GTR_nov2 manual "true" "Target: 9 Chain"
node makeDrillFiles.js drill_input/9chain_lshape.json "9 Chain - L-shape" lshape 9chain_lshape_nov2 manual "true" "Target: 9 Chain"
node makeDrillFiles.js drill_input/9chain_sandwich.json "9 Chain - Sandwich" sandwich 9chain_sandwich_nov2 manual "true" "Target: 9 Chain"
node makeDrillFiles.js drill_input/10chain_GTR.json "10 Chain - GTR" gtr 10chain_GTR_nov2 manual "true" "Target: 10 Chain"
node makeDrillFiles.js drill_input/10chain_lshape.json "10 Chain - L-Shape" lshape 10chain_lshape_nov2 manual "true" "Target: 10 Chain"
node makeDrillFiles.js drill_input/10chain_yayoi.json "10 Chain - Yayoi" yayoi 10chain_yayoi_nov2 manual "true" "Target: 10 Chain"
node makeDrillFiles.js drill_input/11chain_GTR.json "11 Chain - GTR" gtr 11chain_gtr_nov2 manual "true" "Target: 11 Chain"
node makeDrillFiles.js drill_input/11chain_GTR_b.json "11 Chain - GTR" gtr 11chain_gtr_b_nov2 manual "true" "Target: 11 Chain"
node makeDrillFiles.js drill_input/11chain_lshape.json "11 Chain - L-Shape" lshape 11chain_lshape_nov2 manual "true" "Target: 11 Chain"
node makeDrillFiles.js drill_input/11chain_newGTR.json "11 Chain - New GTR" newgtr 11chain_gtr_nov2 manual "true" "Target: 11 Chain"
node makeDrillFiles.js drill_input/11chain_stairs.json "11 Chain - Stairs" stairs 11chain_stairs_nov2 manual "true" "Target: 11 Chain"
node makeDrillFiles.js drill_input/12chain_gtr.json "12 Chain - GTR" gtr 12chain_gtr_nov2 manual "true" "Target: 12 Chain"
node makeDrillFiles.js drill_input/12chain_gtr.json "12 Chain - L-Shape" lshape 12chain_lshape_nov2 manual "true" "Target: 12 Chain"
node makeDrillFiles.js drill_input/12chain_tanakaspecial.json "12 Chain - Tanaka Special" tailing 12chain_tanakaspecial_nov2 manual "true" "Target: 12 Chain"
node makeDrillFiles.js drill_input/13chain_GTR_Kenny.json "13 Chain - GTR" gtr 13chain_gtr_nov2 manual "true" "Target: 13 Chain"
node makeDrillFiles.js drill_input/13chain_yayoi.json "13 Chain - Yayoi" yayoi 13chain_yayoi_nov2 manual "true" "Target: 13 Chain"
node makeDrillFiles.js drill_input/14chain_GTR.json "14 Chain - GTR" gtr 14chain_gtr_nov2 manual "true" "Target: 14 Chain"
node makeDrillFiles.js drill_input/14chain_GTR_cushion.json "14 Chain - GTR with Cushion" gtr 14chain_gtr_cushion_nov2 manual "true" "Target: 14 Chain"
node makeDrillFiles.js drill_input/14chain_newGTR.json "14 Chain - New GTR" newgtr 14chain_newGTR_nov2 manual "true" "Target: 14 Chain"
node makeDrillFiles.js drill_input/14chain_GTR.json "15 Chain - Sandwich" sandwich 15chain_sandwich_nov2 manual "true" "Target: 15 Chain"